services:
  
  frontend:
    build: ./todo_frontend
    ports:
      - 3000:80

  backend:
    build: ./todo_backend
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      DB_HOST: db          
      DB_USER: root        
      DB_PASSWORD: password 
      DB_NAME: todo_app     
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todo_app
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 8080:80

volumes:
  db-data:
