apiVersion: v1
kind: Service
metadata:
  name: todoapp-frontend
spec:
  type: NodePort
  selector:
    app: todoapp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Anda dapat mengganti ini dengan port lain dalam rentang 30000-32767
